name: Boost.Independency test
on: [push]
jobs"
  boost-independency-test-build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Boost.Build
        run: |
          sudo apt-get update
          sudo apt-get install libboost-tools-dev

      - name: Build test
        run: |
          cd test
          b2